language: node_js

stages:
  - name: deploy

jobs:
  include:
    - stage: deploy
      script:
        - echo "NPM Deploying Started ..."

      deploy:
        provider: npm
        email: '979904565@qq.com'
        api_key: "$NPM_TOKEN"
        skip_cleanup: true