language: node_js
node_js:
  - node

stages:
  - name: deploy

jobs:
  include:
    - stage: deploy

      deploy:
        provider: npm
        email: '979904565@qq.com'
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          tags: true